name: microwins
description: "A new Flutter project."
publish_to: 'none'
# The value before the + is the version name shown to users.
# The value after the + is the build number used by app stores.
# The build number must increase before every Google Play upload.
version: 1.2.0+4

environment:
  sdk: ^3.11.1

dependencies:
  audioplayers: ^6.5.0
  cloud_firestore: ^6.1.3
  firebase_auth: ^6.2.0
  firebase_core: ^4.5.0
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
